# Generated by Django 3.1.3 on 2021-02-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_connecttosocialaccount_socialnetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='connecttosocialaccount',
            name='username',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
