# Generated by Django 2.2.4 on 2020-08-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('deleted', 'DELETED')], default='active', max_length=25),
        ),
    ]
