# Generated by Django 3.2 on 2022-08-30 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20220830_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['pk']},
        ),
    ]
