# Generated by Django 3.2 on 2022-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20220830_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_kr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_kr',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
